/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;
import dataset.dataKamar;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class frameKamar extends javax.swing.JFrame {
    dataKamar kamar;

    /**
     * Creates new form frameKamar
     */
    public frameKamar() {
        initComponents();
        this.setLocationRelativeTo(null);
        kamar = new dataKamar();
        
        txtHargaWeekday.setEditable(false);
        txtHargaWeekend.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        cmbTipe = new javax.swing.JComboBox<>();
        cmbKapasitas = new javax.swing.JComboBox<>();
        cmbFasilitas = new javax.swing.JComboBox<>();
        cmbStatus = new javax.swing.JComboBox<>();
        txtHargaWeekday = new javax.swing.JTextField();
        txtHargaWeekend = new javax.swing.JTextField();
        btnSimpanDataKamar = new javax.swing.JButton();
        txtIndex = new javax.swing.JTextField();
        btnTampilDataKamar = new javax.swing.JButton();
        btnKamarToPesan = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Kode Kamar");

        jLabel2.setText("Tipe");

        jLabel3.setText("Kapasitas");

        jLabel4.setText("Fasilitas");

        jLabel5.setText("Status");

        jLabel6.setText("Harga Weekday");

        jLabel7.setText("HargaWeekend");

        cmbTipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Luxury", "Executive" }));
        cmbTipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipeActionPerformed(evt);
            }
        });

        cmbKapasitas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2 Orang", "4 Orang" }));

        cmbFasilitas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Private Beach", "View Laut" }));

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tersedia", "Penuh" }));

        txtHargaWeekend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaWeekendActionPerformed(evt);
            }
        });

        btnSimpanDataKamar.setText("Simpan Data Kamar");
        btnSimpanDataKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanDataKamarActionPerformed(evt);
            }
        });

        txtIndex.setText("0");

        btnTampilDataKamar.setText("Tampilkan Data");
        btnTampilDataKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilDataKamarActionPerformed(evt);
            }
        });

        btnKamarToPesan.setText("Pesan Kamar");
        btnKamarToPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKamarToPesanActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("DATA KAMAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtHargaWeekend, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSimpanDataKamar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbFasilitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbTipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cmbKapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtHargaWeekday, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTampilDataKamar)
                    .addComponent(btnKamarToPesan))
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbFasilitas, cmbKapasitas, cmbStatus, cmbTipe, txtHargaWeekday, txtHargaWeekend, txtKode});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnTampilDataKamar, txtIndex});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnKamarToPesan)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbTipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbKapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbFasilitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtHargaWeekday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtHargaWeekend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanDataKamar)
                    .addComponent(btnTampilDataKamar))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHargaWeekendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaWeekendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaWeekendActionPerformed

    private void cmbTipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipeActionPerformed
        // TODO add your handling code here:
        String pilihTipe = (String) cmbTipe.getSelectedItem();
        
        if (pilihTipe.equals("Luxury")){
            txtHargaWeekday.setText("1000000");
            txtHargaWeekend.setText("2000000");
            cmbKapasitas.setSelectedIndex(0);
            cmbFasilitas.setSelectedIndex(1);
        } else if (pilihTipe.equals("Executive")) {
            txtHargaWeekday.setText("1500000");
            txtHargaWeekend.setText("3000000");
            cmbKapasitas.setSelectedIndex(1);
            cmbFasilitas.setSelectedIndex(0);
        } 
    }//GEN-LAST:event_cmbTipeActionPerformed

    private void btnSimpanDataKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanDataKamarActionPerformed
        // TODO add your handling code here:
        kamar.insertKode(Integer.valueOf(txtKode.getText()));
        kamar.insertTipe(cmbTipe.getSelectedItem().toString());
        kamar.insertKapasitas(cmbKapasitas.getSelectedItem().toString());
        kamar.insertFasilitas(cmbFasilitas.getSelectedItem().toString());
        kamar.insertStatus(cmbStatus.getSelectedItem().toString());
        kamar.insertHargaWeekday(Double.valueOf(txtHargaWeekday.getText()));
        kamar.insertHargaWeekend(Double.valueOf(txtHargaWeekend.getText()));
        
        JOptionPane.showMessageDialog(this, "Data Kamar Berhasil Disimpan");
        
        txtKode.setText("");
        cmbTipe.setSelectedIndex(0);
        cmbKapasitas.setSelectedIndex(0);
        cmbFasilitas.setSelectedIndex(0);
        cmbTipe.setSelectedIndex(0);
        cmbStatus.setSelectedIndex(0);
        txtHargaWeekday.setText("");
        txtHargaWeekend.setText("");
    }//GEN-LAST:event_btnSimpanDataKamarActionPerformed

    private void btnKamarToPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKamarToPesanActionPerformed
        // TODO add your handling code here:
        new framePesan().setVisible(true);
    }//GEN-LAST:event_btnKamarToPesanActionPerformed

    private void btnTampilDataKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilDataKamarActionPerformed
        // TODO add your handling code here:
        int i = Integer.valueOf(txtIndex.getText());
        
        String isiDataKamar = "Kode Kamar : "+kamar.getRecordKode().get(i)+
                              "\nTipe : "+kamar.getRecordTipe().get(i)+
                              "\nKapasitas : "+kamar.getRecordKapasitas().get(i)+
                              "\nFasilitas : "+kamar.getRecordFasilitas().get(i)+
                              "\nStatus : "+kamar.getRecordStatus().get(i)+
                              "\nHarga Weekday : "+kamar.getRecordHargaWeekday().get(i)+
                              "\nHarga Weekend : "+kamar.getRecordHargaWeekend().get(i);
        
        JOptionPane.showMessageDialog(this, isiDataKamar);
    }//GEN-LAST:event_btnTampilDataKamarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameKamar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKamarToPesan;
    private javax.swing.JButton btnSimpanDataKamar;
    private javax.swing.JButton btnTampilDataKamar;
    private javax.swing.JComboBox<String> cmbFasilitas;
    private javax.swing.JComboBox<String> cmbKapasitas;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JComboBox<String> cmbTipe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtHargaWeekday;
    private javax.swing.JTextField txtHargaWeekend;
    private javax.swing.JTextField txtIndex;
    private javax.swing.JTextField txtKode;
    // End of variables declaration//GEN-END:variables
}
